from src.kb.key import Key

num_1 = Key("num 1")
num_2 = Key("num 2")
num_3 = Key("num 3")
num_4 = Key("num 4")
num_5 = Key("num 5")
num_6 = Key("num 6")
num_7 = Key("num 7")
num_8 = Key("num 8")
num_9 = Key("num 9")
num_0 = Key("num 0")
num_enter = Key("num enter")
num_plus = Key("num +")
num_minus = Key("num -")
num_asterisk = Key("num *")
num_slash = Key("num /")
num_dot = Key("num .")

key_1 = Key("1")
key_2 = Key("2")
key_3 = Key("3")
key_4 = Key("4")
key_5 = Key("5")
key_6 = Key("6")
key_7 = Key("7")
key_8 = Key("8")
key_9 = Key("9")
key_a = Key("a")
key_d = Key("d")
caps = Key("capslock")
mouse1 = Key("mouse:1")
mouse2 = Key("mouse:2")
mouse3 = Key("mouse:3")
