key_labels: dict[str, str] = {
    "num 0": "0️⃣",
    "num 1": "1️⃣",
    "num 2": "2️⃣",
    "num 3": "3️⃣",
    "num 4": "4️⃣",
    "num 5": "5️⃣",
    "num 6": "6️⃣",
    "num 7": "7️⃣",
    "num 8": "8️⃣",
    "num 9": "9️⃣",
    "num mult": "*️⃣️",
    "num plus": "➕",
    "num minus": "➖",
    "num /": "➗",
    "num enter": "↩️",
    "num .": "●",
}
