key_labels: dict[str, str] = {
    "num 0": "num 0️⃣ ",
    "num 1": "num 1️⃣ ",
    "num 2": "num 2️⃣ ",
    "num 3": "num 3️⃣ ",
    "num 4": "num 4️⃣ ",
    "num 5": "num 5️⃣ ",
    "num 6": "num 6️⃣ ",
    "num 7": "num 7️⃣ ",
    "num 8": "num 8️⃣ ",
    "num 9": "num 9️⃣ ",
    "num *": "num *️⃣️ ",
    "num +": "num ➕",
    "num -": "num ➖",
    "num /": "num ➗‍‍",
    "num enter": "num ⏎ ",
    "num .": "num 🔴",
    "mouse:1": "🖱️1️⃣ ",
    "mouse:2": "🖱️2️⃣ ",
    "mouse:3": "🖱️3️⃣ ",
    "mouse:4": "🖱️4️⃣ ",
    "mouse:5": "🖱️5️⃣ ",
    "capslock": "⇪",
}
