key_labels: dict[str, str] = {
    "num 0": "num 0",
    "num 1": "num 1",
    "num 2": "num 2",
    "num 3": "num 3",
    "num 4": "num 4",
    "num 5": "num 5",
    "num 6": "num 6",
    "num 7": "num 7",
    "num 8": "num 8",
    "num 9": "num 9",
    "num *": "num *",
    "num +": "num +",
    "num -": "num -",
    "num /": "num /‍",
    "num enter": "num ⏎ ",
    "num .": "num .",
    "mouse:1": "M1",
    "mouse:2": "M2",
    "mouse:3": "M3",
    "mouse:4": "M4",
    "mouse:5": "M5",
    "capslock": "⇪",
}
