from .hotkeys import Key

num_1 = Key("num 1")
num_2 = Key("num 2")
num_3 = Key("num 3")
num_4 = Key("num 4")
num_5 = Key("num 5")
num_6 = Key("num 6")
num_7 = Key("num 7")
num_8 = Key("num 8")
num_9 = Key("num 9")
num_0 = Key("num 0")
num_enter = Key("num enter")
num_plus = Key("num +")
num_minus = Key("num -")
num_asterisk = Key("num *")
num_slash = Key("num /")
num_dot = Key("num .")
